### ISSUE TITLE
Graphical bug in history when dealing with long URLs 

### ISSUE THREAD

**Issue by sjoerd108** [RESTEDClient/RESTED#124]
The history panel's text overflows when dealing with really long URLs. This does not compromise functionality but looks pretty weird non the less.

I've included a screenshot for clarity:
![selection_024](https://user-images.githubusercontent.com/17080530/33168348-f1a8a778-d040-11e7-8a2b-1f8c77ae46d0.png)

This happened on Firefox 57 with the latest version of the extension at the moment: 2.1.1

**Comment by esphen** [comment]
Hehe, that's pretty ugly, yeah.

Thanks for reporting this, I'll add it to the sprint

**Comment by hdwilber** [comment]
Hey!. I could not recreate this issue in Firefox 59 nor Chrome.
![selection_039](https://user-images.githubusercontent.com/16395551/38327979-a786c5a0-3817-11e8-82e5-0c5de036505f.png)

It is very rare. Or perhaps, is it necessary to close this one?

**Comment by sjoerd108** [comment]
It only happens when the query parameter is really long. It seems like it refuses to word wrap on long query params for some reason. Here's a screenshot of this behaviour:
![image](https://user-images.githubusercontent.com/17080530/38351823-7a229df6-38b1-11e8-9d74-d6b4d8f892ce.png)
