### ISSUE TITLE
Send a list of values in JSON

### ISSUE THREAD

**Issue by Joanfv** [RESTEDClient/RESTED#126]
I'm trying to send a list of Guids using JSON syntax and other combinations but always having a Bar Request response. I cannot find documentation or examples about sending a parameter that is a list.

Thanks

**Comment by esphen** [comment]
Hi there,

This is a feature in the upcoming 2.2.0 release. There you will be able to send a value of `[1,2,3]` or `["foo"," bar"]` and have it be properly parsed into a JSON type. Have not been able to work on 2.2.0 for a while, but I guess I should release what is done thus far and move the outstanding issues to the release after this. Stay tuned!

See https://github.com/RESTEDClient/RESTED/issues/114
