### ISSUE TITLE
Firefox 66.0.3 AddOn cannot install

### ISSUE THREAD

**Issue by TKDevPro** [RESTEDClient/RESTED#158]
Since Firefox 66.0.3 (at my PC) RESTED doesn't work. Firefox has deactivated the AddOn because
https://support.mozilla.org/en-US/kb/add-on-signing-in-firefox

**Comment by esphen** [comment]
Yep, Mozilla's fault. Their signing cert expired. Wait for a fix or see this blog.

https://blog.mozilla.org/addons/2019/05/04/update-regarding-add-ons-in-firefox/
