### ISSUE TITLE
Opera extension shows blank white page

### ISSUE THREAD

**Issue by ShadauxCat** [RESTEDClient/RESTED#162]
It appears to be referencing a file called "rested.js", which does not exist. I can't find it anywhere in the repo either so I'm assuming there's some build process that creates this. Right now the extension in Opera is unusable.

**Comment by esphen** [comment]
Wow, that sucks. Wonder how that happened. Anyway, I just uploaded a new version for review to the Opera guys. If you need to use the extension you can download the nex-file from the releases page meanwhile.

Thanks for the heads up

**Comment by esphen** [comment]
Just got published, seems to work from my end.

**Comment by ShadauxCat** [comment]
Thanks for the quick reply, looks like it works on my end as well now!
