### ISSUE TITLE
Not able to add request into collections

### ISSUE THREAD

**Issue by neeraj-bansal** [RESTEDClient/RESTED#179]

**Comment by neeraj-bansal** [comment]
in firefox

**Comment by neoacevedo** [comment]
Just today I'm unable to add a request to an existing collection. I could add some days ago some URL requests but today, the popup to add to a collection isn't displayed.

**Comment by noehmeier** [comment]
I have the same problem, i can not add any request to an existing collection.

**Comment by RDCH106** [comment]
Impossible to add a request to an existing collection or in a new one. The button with the + symbol for collection addition doesn't do anything.

I am using:

- Firefox Browser 96.0.3 (64-bit)
- RESTED 2.5.0 

Tested in a normal and private session with the same result.

**Comment by bklingen-calpoly** [comment]
Same problem on Chrome Version 121.0.6167.85 (Official Build) (arm64) RESTED 2.5.0

**Comment by neeraj-bansal** [comment]
closing this since no response.
