### ISSUE TITLE
No UI to launch RESTED

### ISSUE THREAD

**Issue by entinio** [RESTEDClient/RESTED#241]
Just installed it on Firefox... how do we launch it ?

1- nothing about how to launch it in your Readme
2- no RESTED button in the tool bar
3- no details in the modules menu
4- no shortcut detailed anywhere

Is it  a bug or a lack of information ?

**Comment by dtmonterrey** [comment]
There's an icon on the bookmark toolbar. Enable/disable the bookmark toolbar with CTRL+SHIFT+b
