### ISSUE TITLE
Allow increasing syntax highlighting limit?

### ISSUE THREAD

**Issue by Gert-dev** [RESTEDClient/RESTED#74]
Hello

Not sure if this is actually a limitation of a 3rd party library or an artificially set limit, but would it be possible to allow increasing the syntax highlighting limit? It's a good safeguard, but in some cases I'd prefer waiting a bit longer for syntax highlighting to complete than not having it at all.

Thanks in advance

**Comment by esphen** [comment]
Hi Gert,

Yeah, it was a bit silly of me to not make this user configurable. I totally agree with you. I'll fix that in the next version released after 2.0 (it is already in review)

**Comment by esphen** [comment]
Got more important issues for the next milestone, I'm afraid. I'll get back to this later.
